version: '2'

services:

  app:
    build: .
    container_name: taller_crud_system
    restart: always
    depends_on:
      - mysql
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://98.82.9.114:3306/properties?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: mainuser
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network: